version: '3.8'

services:
  hirovo-api:
    build:
      context: ../../
      dockerfile: _devops/docker/Dockerfile-modules-worker
    container_name: hirovo-api-container
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=HirovoDb;User=sa;Password=FRAudnxd4rzcVPt;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - hirovo-network

  iam-api:
    build:
      context: ../../
      dockerfile: _devops/docker/Dockerfile-modules-iam
    container_name: iam-api-container
    ports:
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=HirovoDb;User=sa;Password=FRAudnxd4rzcVPt;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - hirovo-network

  api-gateway:
    build:
      context: ../../
      dockerfile: _devops/docker/Dockerfile-api-gateway
    container_name: hirovo-api-gateway
    ports:
      - "5000:8080"
    depends_on:
      - hirovo-api
      - iam-api
    networks:
      - hirovo-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "FRAudnxd4rzcVPt"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - hirovo-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-gateway
    networks:
      - hirovo-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"

volumes:
  certbot-etc:
  certbot-var:

networks:
  hirovo-network:
    driver: bridge
