FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN apt-get update && apt-get install -y \
    git \
    openssh-client

# Git ayarları
RUN git config --global user.name "CI/CD-BOT" && \
    git config --global user.email "bot@hirovo.com" && \
    git config --global push.default matching && \
    git config --global pull.rebase false && \
    git config --global http.sslVerify false && \
    mkdir -p /root/.ssh

# SSH anahtar dosyasını kopyala
COPY _devops/ssh/id_rsa_mobileapp /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa && ssh-keyscan github.com >> /root/.ssh/known_hosts

# ArfBlocks CLI yükle
RUN dotnet tool install --global Arfware.ArfBlocks-cli --version 2.0.0

# CLI erişimi
ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /maden/backend
COPY . .
COPY BusinessModules ./BusinessModules
COPY BaseModules ./BaseModules
COPY _devops ./_devops


# Geçici klasörleri oluştur
RUN mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/api/business_modules/hirovo && \
    mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/api/base_modules/iam && \
    mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/errors/locales/modules/common && \
    mkdir -p /maden/backend/_devops/tmp/webapp/common/hirovo-api/src/errors/locales/modules/workers

# ArfBlocks CLI çalıştırackend/_devops/tmp/webapp/common/* /maden/backend/webapp/c
RUN arfblocks-cli exec --file /maden/backend/_devops/arfblocks-cli/hirovo.arfblocks-cli.json
RUN arfblocks-cli exec --file /maden/backend/_devops/arfblocks-cli/iam.arfblocks-cli.json

# ErrorCodeExporter çalıştır (hata alsa bile devam et)
RUN dotnet run --project /maden/backend/Jobs/SpecialPurpose/DevTasks/ErrorCodeExporter/ErrorCodeExporter.csproj || true

# 📁 Çıktıyı `webapp` klasörüne kopyala
RUN mkdir -p /maden/backend/webapp/common && \
    if [ -d "/maden/backend/_devops/tmp/webapp/common" ] && [ "$(ls -A /maden/backend/_devops/tmp/webapp/common)" ]; then \
    cp -r /maden/backend/_devops/tmp/webapp/common/* /maden/backend/webapp/common/; \
    fi
