FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /DockerSource

# Copy everything else and build
COPY ./Gateways/Api/Gateways.ApiGateway.Api .
WORKDIR /DockerSource
RUN dotnet restore
RUN dotnet publish -c release -o /Output --no-restore

# Final stage / image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build /Output .

RUN apt update && apt install tzdata -y
ENV TZ="Europe/Istanbul"

EXPOSE 8080
ENTRYPOINT ["dotnet", "Gateways.ApiGateway.Api.dll"]
