FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build 

# Copy everything else and build
COPY . /src/backend
WORKDIR /src/backend

# INSTALL ARFBLOCKS-CLI
RUN dotnet tool install --global Arfware.ArfBlocks-cli --version 2.0.0
ENV PATH="${PATH}:/root/.dotnet/tools"

# GIT OPERATIONS
ARG git_username
ARG git_password

RUN git config --global pull.rebase false
RUN git config --global user.name "CI/CD-BOT"
RUN git config --global user.email "bot.cicd@hirovo.com.tr"
RUN git config --global push.default matching
RUN git config --global http.sslVerify false

RUN echo "Frontend"
RUN git clone https://github.com/mstfa6060/maden-frontend.git /src/webapp/ --branch master

RUN ls -la
RUN echo "********************************************"

# GENERATE API DOC
RUN arfblocks-cli exec --file /src/backend/_devops/arfblocks-cli/hirovo.arfblocks-cli.json
RUN arfblocks-cli exec --file /src/backend/_devops/arfblocks-cli/iam.arfblocks-cli.json

# GENERATE ERROR CODES
RUN dotnet run --project Jobs/SpecialPurpose/DevTasks/ErrorCodeExporter/ 

WORKDIR /src/webapp

# Add API Docs to Git Stage
RUN sed -i 's/IByte\[\]/Test/g' common/maden-api/src/api/business_modules/hirovo/index.ts
RUN sed -i 's/__ERROR_TYPE_NOT_HANDLED__/any/g' common/maden-api/src/api/business_modules/hirovo/index.ts 

RUN git add common/maden-api/src/api/business_modules/hirovo/index.ts \
    common/maden-api/src/api/base_modules/iam/index.ts

# Add Error Code Files
RUN git add common/maden-api/src/errors/locales/modules/iam/tr.ts \
    common/maden-api/src/errors/locales/modules/hirovo/tr.ts \
    common/maden-api/src/errors/locales/modules/definitions/tr.ts

RUN git commit -m "API: Updated API Documentation #skipci" || true
RUN git pull
RUN git push

## Mobile
RUN echo "Mobile"
RUN git clone https://github.com/mstfa6060/maden-k8s.git /src/mobileapp/ --branch main

WORKDIR /src/mobileapp
Run ls -la

# Add API Docs to Git Stage
RUN cp /src/webapp/common/maden-api/src/api/business_modules/hirovo/index.ts              /src/mobileapp/common/maden-api/docs/business_modules/hirovo/index.ts 
RUN cp /src/webapp/common/maden-api/src/api/base_modules/iam/index.ts                  /src/mobileapp/common/maden-api/docs/base_modules/iam/index.ts 

# Error Message
RUN cp /src/webapp/common/maden-api/src/errors/locales/modules/hirovo/tr.ts              /src/mobileapp/common/maden-api/src/errors/locales/modules/hirovo/tr.ts 
RUN cp /src/webapp/common/maden-api/src/errors/locales/modules/iam/tr.ts              /src/mobileapp/common/maden-api/src/errors/locales/modules/iam/tr.ts 


# Add API Docs to Git Stage
RUN git add /src/mobileapp/common/maden-api/docs/business_modules/hirovo/index.ts  \
    /src/mobileapp/common/maden-api/docs/base_modules/iam/index.ts

RUN git add /src/mobileapp/common/maden-api/src/errors/locales/modules/hirovo/tr.ts  \
    /src/mobileapp/common/maden-api/src/errors/locales/modules/iam/tr.ts

RUN git commit -m "API: Updated API Documentation #skipci" || true
RUN git pull
RUN git push