# Base image
FROM mcr.microsoft.com/dotnet/sdk:8.0

# SSH, Git, diğer ihtiyaçlar
RUN apt-get update && apt-get install -y \
    openssh-client \
    git

# SSH klasörünü oluştur
RUN mkdir -p /root/.ssh

# ArfBlocks CLI yükle
RUN dotnet tool install --global Arfware.ArfBlocks-cli --version 2.0.0
ENV PATH="${PATH}:/root/.dotnet/tools"

# Git ayarları
RUN git config --global user.name "CI/CD-BOT"
RUN git config --global user.email "bot@hirovo.com"
RUN git config --global pull.rebase false
RUN git config --global push.default matching
RUN git config --global http.sslVerify false

# Çalışma dizini
WORKDIR /maden/backend  # Bu dizin sunucundaki backend projesi

# Projeyi kopyala
COPY . .
COPY Jobs/SpecialPurpose/DevTasks/ErrorCodeExporter /maden/backend/Jobs/SpecialPurpose/DevTasks/ErrorCodeExporter
COPY BusinessModules/Hirovo /maden/backend/BusinessModules/Hirovo
COPY BaseModules/IAM /maden/backend/BaseModules/IAM
COPY Common/Services /maden/backend/Common/Services
COPY Common/Definitions /maden/backend/Common/Definitions
COPY Common/Domain /maden/backend/Common/Domain
COPY BusinessModules /maden/backend/BusinessModules
COPY BaseModules /maden/backend/BaseModules


# SSH key’i kopyala (Jenkins pipeline’dan geliyor)
COPY _devops/ssh/id_rsa_mobileapp /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# GitHub host’u ekle
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

# ArfBlocks çıktısı için gerekli dizinleri oluştur
RUN mkdir -p /maden/webapp/common/hirovo-api/src/api/business_modules/hirovo
RUN mkdir -p /maden/webapp/common/hirovo-api/src/api/base_modules/iam

# Hirovo API dokümantasyonunu üret
RUN arfblocks-cli exec --file /maden/backend/_devops/arfblocks-cli/hirovo.arfblocks-cli.json

# IAM API dokümantasyonunu üret
RUN arfblocks-cli exec --file /maden/backend/_devops/arfblocks-cli/iam.arfblocks-cli.json

# Error Code Exporter
RUN dotnet run --project /maden/backend/Jobs/SpecialPurpose/DevTasks/ErrorCodeExporter/ErrorCodeExporter.csproj

# 📦 Çıktıyı dışa aktarmak için: host’a kopyalanabilir hale getir
RUN mkdir -p /maden/backend/_devops/tmp/webapp/common && \
    cp -r /maden/webapp/common/* /maden/backend/_devops/tmp/webapp/common/
